site_name: GEOG3300 and AGRI3003 
repo_url: http://geog3300-agri3003.github.io./coursebook
repo_name: GEOG3300 and AGRI3003

theme:
    name: material
    features:
      - content.code.copy
      - navigation.tabs
      - navigation.top
      - navigation.footer
    palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# extra_css:
#     - css/extra.css

plugins:
- search
- mkdocs-jupyter:
    include_source: True
    ignore_h1_titles: True
    allow_errors: false
    ignore: ["conf.py"]
    execute: False
    execute_ignore:
        ["notebooks/*.ipynb"]

markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/"

nav:
  - Home: index.md
  - Course Outline: course-outline.md
  - AI and LLMs: 
      - ai/overview-and-tools.md
      - ai/example-uses.md
      - ai/prompt-engineering.md
  - Notebooks:
      - notebooks/week-1_1.ipynb
      - notebooks/week-1_2.ipynb
      - notebooks/week-1_practice.ipynb
      - notebooks/week-2_1.ipynb
      - notebooks/week-2_2.ipynb
      - notebooks/week-2_practice.ipynb
      - notebooks/week-3_1.ipynb
      - notebooks/week-3_2.ipynb
      - notebooks/week-3_practice.ipynb
      - notebooks/week-4_1.ipynb
      - notebooks/week-4_2.ipynb
      - notebooks/week-4_practice.ipynb
      - notebooks/week-5_1.ipynb
      - notebooks/week-5_2.ipynb
      - notebooks/week-6_1.ipynb
      - notebooks/week-6_2.ipynb
      - notebooks/week-7_1.ipynb